builds:
  - main: main.go
    binary: terraform-provider-openapi_v{{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
    - CGO_ENABLED=0
    flags:
    - -a
    - -tags="netgo"
    ldflags:
    - -s -w -extldflags "-static" -X "github.com/dikhan/terraform-provider-openapi/openapi/v2/version.Version={{.Version}}" -X "github.com/dikhan/terraform-provider-openapi/openapi/v2/version.Commit={{.Commit}}" -X "github.com/dikhan/terraform-provider-openapi/openapi/v2/version.Date={{.Date}}"

release:
  name_template: "v{{.Version}}"
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

archives:
  - id: terraform-provider-openapi-archives
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{.Version}}_checksums.txt"